channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2022.2.1
  - certifi=2021.10.8
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.3
  - openssl=1.1.1n
  - pip=21.2.4
  - python=3.9.7
  - readline=8.1.2
  - sqlite=3.38.0
  - tk=8.6.11
  - tzdata=2021e
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - dirtyjson==1.0.7
    - filelock==3.6.0
    - frozenlist==1.3.0
    - fsspec==2022.2.0
    - future==0.18.2
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - huggingface-hub==0.4.0
    - idna==3.3
    - importlib-metadata==4.11.3
    - joblib==1.1.0
    - markdown==3.3.6
    - multidict==6.0.2
    - nltk==3.7
    - numpy==1.22.3
    - oauthlib==3.2.0
    - packaging==21.3
    - pillow==9.0.1
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pyparsing==3.0.7
    - pytorch-lightning==1.5.10
    - pyyaml==6.0
    - regex==2022.3.15
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sacremoses==0.0.49
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - sentence-transformers==2.2.0
    - sentencepiece==0.1.96
    - setuptools==59.5.0
    - six==1.16.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - tokenizers==0.11.6
    - torch==1.11.0
    - torchmetrics==0.7.2
    - torchvision==0.12.0
    - tqdm==4.63.0
    - transformers==4.17.0
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - werkzeug==2.0.3
    - yarl==1.7.2
    - zipp==3.7.0
