channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.0.5
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - ipykernel=6.13.0
  - ipython=8.2.0
  - jedi=0.18.1
  - jupyter_client=7.0.6
  - jupyter_core=4.9.2
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - matplotlib-inline=0.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.5
  - openssl=1.1.1n
  - packaging=21.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=21.2.4
  - prompt-toolkit=3.0.29
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - python=3.9.7
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=19.0.2
  - readline=8.1.2
  - six=1.16.0
  - sqlite=3.38.0
  - stack_data=0.2.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - tzdata=2021e
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.11
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - astroid==2.11.3
    - async-timeout==4.0.2
    - attrs==21.4.0
    - black==22.3.0
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - click==8.0.4
    - dataclass-csv==1.4.0
    - dill==0.3.4
    - dirtyjson==1.0.7
    - docstring-parser==0.13
    - filelock==3.6.0
    - frozenlist==1.3.0
    - fsspec==2022.2.0
    - future==0.18.2
    - google-auth==2.6.2
    - google-auth-oauthlib==0.4.6
    - grpcio==1.44.0
    - huggingface-hub==0.4.0
    - idna==3.3
    - importlib-metadata==4.11.3
    - isort==5.10.1
    - joblib==1.1.0
    - jsonargparse==4.7.0
    - lazy-object-proxy==1.7.1
    - markdown==3.3.6
    - mccabe==0.7.0
    - mpu==0.23.1
    - multidict==6.0.2
    - mypy-extensions==0.4.3
    - nltk==3.7
    - numpy==1.22.3
    - oauthlib==3.2.0
    - pathspec==0.9.0
    - pillow==9.0.1
    - platformdirs==2.5.2
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pylint==2.13.7
    - pyparsing==3.0.7
    - pytorch-ignite==0.4.8
    - pytorch-lightning==1.5.10
    - pyyaml==6.0
    - regex==2022.3.15
    - requests==2.27.1
    - requests-oauthlib==1.3.1
    - rsa==4.8
    - sacremoses==0.0.49
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - sentence-transformers==2.2.0
    - sentencepiece==0.1.96
    - setuptools==59.5.0
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - tokenizers==0.11.6
    - tomli==2.0.1
    - torch==1.11.0
    - torch-metrics==1.1.7
    - torchmetrics==0.7.2
    - torchvision==0.12.0
    - tqdm==4.63.0
    - transformers==4.17.0
    - typing-extensions==4.1.1
    - urllib3==1.26.9
    - werkzeug==2.0.3
    - wrapt==1.14.0
    - yarl==1.7.2
    - zipp==3.7.0
