trainer:
  max_epochs: 2
model:
  class_path: models.IntentModel
  init_args:
    n_classes: 5
    model_name : roberta-base
data:
  class_path: data_modules.IntentDataModule
  init_args:
    batch_size: 20
    model_name : roberta-base
    max_token_len : 128