trainer:
  default_root_dir: lightning_logs/intent
  max_epochs: 1
  gpus:
    - 0
model:
  class_path: models.ContrastiveIntentModel
  init_args:
    model_name : sentence-transformers/all-MiniLM-L6-v2
data:
  class_path: data_modules.ContrastiveIntentDataModule
  init_args:
    batch_size: 50
    model_name : sentence-transformers/all-MiniLM-L6-v2
    num_workers: 0
    max_token_len: 64