trainer:
  max_epochs: 1
  gpus:
    - 0
model:
  class_path: models.SlotNameModel
  init_args:
    model_name : sentence-transformers/all-MiniLM-L6-v2
    loss_func_name: OnlineContrastiveLoss
data:
  class_path: data_modules.SlotNameDataModule
  init_args:
    batch_size: 30
    model_name : sentence-transformers/all-MiniLM-L6-v2
    num_workers: 0
    max_token_len: 64